### PR TITLE
Fix #7 - Try catch regularly broken translating from Dex --> Java

### LINKED ISSUE #7: Round-trip D --> J --> D ... is unstable with try-catch block handlers
Converting from Dex to Java to Dex back to Java fails on the `068-classloader` sample.

StackTrace:
```
Caused by: com.android.tools.r8.errors.CompilationError: Different stack heights at jump target: 0 != 1
	at com.android.tools.r8.ir.conversion.CfState.merge(CfState.java:131)
	at com.android.tools.r8.ir.conversion.CfState.merge(CfState.java:126)
	at com.android.tools.r8.ir.conversion.CfSourceCode.recordStateForTarget(CfSourceCode.java:587)
	at com.android.tools.r8.ir.conversion.CfSourceCode.buildInstruction(CfSourceCode.java:567)
	at com.android.tools.r8.ir.conversion.CfSourceCode.buildInstruction(CfSourceCode.java:574)
	at com.android.tools.r8.ir.conversion.IRBuilder.processWorklist(IRBuilder.java:924)
	at com.android.tools.r8.ir.conversion.IRBuilder.build(IRBuilder.java:667)
	at com.android.tools.r8.graph.CfCode.internalBuild(CfCode.java:758)
	at com.android.tools.r8.graph.CfCode.internalBuildPossiblyWithLocals(CfCode.java:664)
	at com.android.tools.r8.graph.CfCode.buildIR(CfCode.java:613)
	at com.android.tools.r8.graph.ProgramMethod.buildIR(ProgramMethod.java:38)
	at com.android.tools.r8.graph.ProgramMethod.buildIR(ProgramMethod.java:32)
	at com.android.tools.r8.ir.conversion.IRConverter.rewriteDesugaredCodeInternal(IRConverter.java:494)
	at com.android.tools.r8.ir.conversion.PrimaryD8L8IRConverter.rewriteNonDesugaredCodeInternal(PrimaryD8L8IRConverter.java:383)
	at com.android.tools.r8.ir.conversion.PrimaryD8L8IRConverter.lambda$rewriteNonDesugaredCode$4(PrimaryD8L8IRConverter.java:368)
	at com.android.tools.r8.ir.conversion.PrimaryD8L8IRConverter.rewriteNonDesugaredCode(PrimaryD8L8IRConverter.java:364)
	at com.android.tools.r8.ir.conversion.PrimaryD8L8IRConverter.convertMethod(PrimaryD8L8IRConverter.java:165)
	at com.android.tools.r8.ir.conversion.D8MethodProcessor.processMethod(D8MethodProcessor.java:164)
	at com.android.tools.r8.ir.conversion.PrimaryD8L8IRConverter.convertMethods(PrimaryD8L8IRConverter.java:130)
	at com.android.tools.r8.ir.conversion.ClassConverter.convertMethods(ClassConverter.java:227)
	at com.android.tools.r8.ir.conversion.ClassConverter$DefaultClassConverter.convertClass(ClassConverter.java:245)
	at com.android.tools.r8.ir.conversion.ClassConverter.lambda$internalConvertClasses$2(ClassConverter.java:162)
	at com.android.tools.r8.utils.ThreadUtils.lambda$processItems$5(ThreadUtils.java:106)
	at com.android.tools.r8.utils.ThreadUtils.processItems(ThreadUtils.java:120)
	at com.android.tools.r8.utils.ThreadUtils.processItems(ThreadUtils.java:106)
	at com.android.tools.r8.ir.conversion.ClassConverter.internalConvertClasses(ClassConverter.java:160)
	at com.android.tools.r8.ir.conversion.ClassConverter.convertClasses(ClassConverter.java:66)
	at com.android.tools.r8.ir.conversion.PrimaryD8L8IRConverter.convertClasses(PrimaryD8L8IRConverter.java:295)
	at com.android.tools.r8.ir.conversion.PrimaryD8L8IRConverter.convert(PrimaryD8L8IRConverter.java:69)
	... 22 more
```

The output of multiple round-trip passes is expected to be lossy, but not outright fail.

### PR DESCRIPTION
**Pull request by Col-E**
Pain and suffering

### CODE REVIEW

File: src/main/java/com/android/tools/r8/ir/conversion/DexSourceCode.java [hunk 1]
```diff
@@ -171,9 +176,77 @@ public void buildInstruction(
...
+
+      // Move into dummy first register. Should act like just like a POP.
+      // Again, this is fine because the exception isn't used.
+      // If it were used, the instruction here would be a 'DexMoveException' which we checked for earlier.
+
+
+      Set<Phi> latestBlockPhis = builder.getLatestBlockPhis();
+      DexMoveException dexMoveException = new DexMoveException(0);
+      dexMoveException.buildIR(builder);
+      builder.resetLatestBlockPhis(latestBlockPhis);
```
Comment (Col-E) [inline src/main/java/com/android/tools/r8/ir/conversion/DexSourceCode.java]: The resetting here is a complete hack to see what happens if we ignore the complaint about phi's from the `MoveException` not being addressed properly.

I have no idea how to address them properly, but I'm hopeful that once that is figured out, this solution will work.

Comment (Col-E) [reply src/main/java/com/android/tools/r8/ir/conversion/DexSourceCode.java]: Removed and replaced with a better fix

**Comment by Col-E** [comment]
There are a few edge cases remaining, but this is _mostly_ resolved now. Merging so dex-translator can pull in the updated logic.
